### ISSUE TITLE
a questiuon on fix CarFusion filename errors

### ISSUE THREAD

**Issue by Dracarys077** [orhir/PoseAnything#10]
Excuse me, when processing carFusion Dataset, I still have some problems. Can you explain more clearly where is the annotation files of the carFusion Dataset. The code "ann_files = os.path.join(carfusion_dir_path, 'annotations')" in tools/fix_carfusion.py, I can't find the annotations?

**Comment by orhir** [comment]
Hi sorry for the late response.

You should first extract the annotations using the original script. Then use our fix.

We will try to provide a more thorough explanation in the following week.

**Comment by orhir** [comment]
The annotations files need to be extracted using the official script.
Please take a look at the setup .sh file where the script is being called:
https://github.com/dineshreddy91/carfusion_to_coco/blob/master/carfusion_coco_setup.sh

Let me know if you have any more issues with this dataset.

**Comment by orhir** [comment]
Closing the issue, if you need further assistance please open a new issue.
