### ISSUE TITLE
Dataset Format

### ISSUE THREAD

**Issue by aniri15** [orhir/PoseAnything#12]
Hello,

Thanks for posting such a great work. I want to download the datasets from different sources as written in guide, but met the problem of format of the dataset organization. In MP100, it has 8 main categories, and a lot subcategories, should it be organized according the subcategories or main categories?

The mp100 lists a category named sling_dress, but it is the subcategory, if using subcategories, for instance, AP-10K has 34 categories, but the downloaded dataset only contains one folder ‘data’, how should I split different categories from this.

Thanks a lot.
Aniri

**Comment by orhir** [comment]
Hi and thank you for showing interest in our work.
Please see issue #11, where we included the complete link list for the dataset.
This should show how to build the links required for each category.

**Comment by aniri15** [comment]
Hello orhir,

Thanks a lot for your reply, it is very helpful. In addition, I also want to know is it possible to test provided check points and config only on one dataset(for example coco)? I tested using them provided in 1 shot and 5 shot model, but test file in annotation required the complete dataset as following:

FileNotFoundError: [Errno 2] No such file or directory: 'data/mp100/images/camel_face/camel_92.jpg'

If I link all datasets(like camel_face) to coco dataset, is it feasible? 
Thanks in advance.

**Comment by orhir** [comment]
Unfortunately, I don't think that linking all links to the same dataset should work.
You can, however, parse the JSON annotations to include only the categories you are interested in.
This way, the annotations will point only to the images of the specific subset.

The annotations format is COCO compatible and is pretty easy to understand, so it shouldn't be to hard.
Good luck.

**Comment by aniri15** [comment]
Hello,
Thanks for your reply, it works now. Also, I would like to display the predicted keypoints from the result_keypoints.json and compare it with the ground truth keypoints from mp100_split3_test.json, I rendered them and found them are not quite similar. Maybe the accurate position should not be directly loaded from the result_keypoints.json, could you give me some hints, my result picture and code are as following:

![Screenshot from 2024-11-17 13-36-18](https://github.com/user-attachments/assets/3337990d-a632-4851-b01e-277ea2c1c42a)

import os
import json
import cv2
import numpy as np
import matplotlib.pyplot as plt

def load_image(image_dir, file_name):
    """
    Load an image by its file name.
    """
    image_path = os.path.join(image_dir, file_name)
    if not os.path.exists(image_path):
        print(f"Image with file name {file_name} not found.")
        return None

    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    return image

def load_keypoints(json_path, image_id):
    """
    Load keypoints from the standard JSON format.
    """
    with open(json_path, 'r') as f:
        data = json.load(f)

    image_info = next((img for img in data["images"] if img["id"] == image_id), None)
    if image_info is None:
        print(f"Image with ID {image_id} not found in JSON file.")
        return None, None

    file_name = image_info["file_name"]
    keypoints_data = next((ann for ann in data["annotations"] if ann["image_id"] == image_id), None)
    if keypoints_data is None:
        print(f"Keypoints for image ID {image_id} not found in JSON file.")
        return None, file_name

    keypoints_raw = keypoints_data['keypoints']
    keypoints = [(keypoints_raw[i], keypoints_raw[i+1], keypoints_raw[i+2]) for i in range(0, len(keypoints_raw), 3)]
    return keypoints, file_name

def load_keypoints_from_alt_json(alt_json_path, image_id):
    """
    Load keypoints from the alternative JSON format.
    """
    with open(alt_json_path, 'r') as f:
        data = json.load(f)

    keypoints_data = next((entry for entry in data if entry["image_id"] == image_id), None)
    if keypoints_data is None:
        print(f"Keypoints for image ID {image_id} not found in alternative JSON file.")
        return None

    keypoints = [(kp[0], kp[1], kp[2]) for kp in keypoints_data["keypoints"]]
    return keypoints

def visualize_combined_keypoints(image, keypoints_list, colors=['red', 'blue']):
    """
    Visualize combined keypoints from multiple sources on the image.
    """
    plt.figure(figsize=(8, 8))
    plt.imshow(image)

    for idx, keypoints in enumerate(keypoints_list):
        color = colors[idx % len(colors)]
        for (x, y, conf) in keypoints:
            if conf > 0.3:  # Optional threshold to display only confident keypoints
                plt.scatter(x, y, s=50, color=color, edgecolors='black')

    plt.axis('off')
    plt.show()

# Example usage
if __name__ == "__main__":
    image_dir = "/home/aniri/Guided research/PoseAnything/data/mp100"
    json_path = "/home/aniri/Guided research/PoseAnything/data/mp100/annotations/mp100_split3_test.json"
    alt_json_path = "/home/aniri/Guided research/PoseAnything/test_result_keypoints/result_keypoints.json"
    #alt_json_path = "/home/aniri/Guided research/PoseAnything/result_keypoints.json"
    image_id = 7200000000428050  # Replace with actual image ID

    # Load keypoints from standard JSON
    keypoints1, file_name = load_keypoints(json_path, image_id)

    # Load keypoints from alternative JSON
    keypoints2 = load_keypoints_from_alt_json(alt_json_path, image_id)

    if file_name:
        # Load image based on file name
        image = load_image(image_dir, file_name)
        if image is not None and keypoints1 is not None and keypoints2 is not None:
            # Visualize combined keypoints from both sources
            visualize_combined_keypoints(image, [keypoints1, keypoints2])

**Comment by orhir** [comment]
I'm not sure, but I guess you should use the bounding box data.
Our approach is top-down, which means we assume a bounding box cropped around the object.
However, I guess you can get more help in the official MMPose regarding output visualizations as we use  their framework.
