### ISSUE TITLE
The training dataset build encountered a sample error, which may be due to the "person" class in the annotation file mp100_split1_train.json？

### ISSUE THREAD

**Issue by oopsRookie** [orhir/PoseAnything#13]
When I run train.py with config file base_split1_config, I encountered an error during the random sampling process while building train dataset.
Here is debug info and error tracestack :

```
random_paired_samples- self.cat2obj[cls]: 72 []
Traceback (most recent call last):
  File "/root/conda/envs/pa/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/UserData/PoseAnything/models/datasets/datasets/mp100/transformer_dataset.py", line 65, in __init__
    self.random_paired_samples()
  File "/home/UserData/PoseAnything/models/datasets/datasets/mp100/transformer_dataset.py", line 82, in random_paired_samples
    shot = random.sample(self.cat2obj[cls], self.num_shots + 1)
  File "/root/conda/envs/pa/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```
I debug [transformer_dataset.py](https://github.com/orhir/PoseAnything/blob/main/models/datasets/datasets/mp100/transformer_dataset.py#L81) and add following code to Line 81
```
if len(self.cat2obj[cls]) == 0:
   print("random_paired_samples- self.cat2obj[cls]:",cls,self.cat2obj[cls])
```
The print info shows `random_paired_samples- self.cat2obj[cls]: 72 []` that means `cat2obj[72]` is an empty list.
So the original code line 81 `shot = random.sample(self.cat2obj[cls], self.num_shots + 1)` raise ValueError("Sample larger than population or is negative").

And then I go to mp100_split1_train.json and find class `person` holds id `72` and keyword person only occurs 4 times in this file. (other classes occur hundred times)
![image](https://github.com/user-attachments/assets/28f7db91-e721-44de-8b77-efe3db17efe2)
And I find class `person `is not in MP100 official class categories.

How should I handle this problem? Delete class person annotation in mp100_split1_train.json? Or modify code or some other ways?

> By the way, mp100_split2_train.json, mp100_split3_train.json and mp100_split5_train.json also have class `person `(id:72)

Thanks for your time.

**Comment by orhir** [comment]
Hi,

It may be a dataset construction error.

The MP100 dataset annotation files include both image info (which includes a category id field), and category info (which includes id and name).

Please note that the ‘person’ field you see is the name of a category, which may be different from the symlink that appears in the dataset constructions instructions.

To find the missing category symlink, you should find an image with category id field XX (or for your case, 72).
This can be done by loading the JSON file and iterating through the image entries with a simple script.
When found, the image path will reveal what symlink is really missing.

**Comment by oopsRookie** [comment]
Thank you for your detailed explanation. 
I finally fix this problem caused by dataset construction of COCO/merged. 
Thank you very much.
