### ISSUE TITLE
How to add points using terminal like we did in OpenXLab?

### ISSUE THREAD

**Issue by haoz19** [orhir/PoseAnything#6]
Hello,

Thanks for sharing such a wonderful work!

How could we add points and edges and in what form when we are using the terminal?

Thanks!
Hao

**Comment by orhir** [comment]
Hi, thank you for showing interest in our work.

First, we highly recommend using the Gradio app provided.

For the terminal code (the name is a bit misleading, it involves CV2 visualizations) you first mark the nodes on the pop-up image, and after finishing (pressing enter) you mark the limbs, similar to the OpenXLab demo.

**Comment by haoz19** [comment]
Thanks so much for your very fast reply! 

Cause I want to use this wonderful model in our system, and we want to automatically input key points of the support image. Can you give me some instructions on how to do that? 

I guess there will be a file generated after I mark the node and limbs, so can I just try to modify that file or just generate that file?

Many Thanks!

**Comment by orhir** [comment]
The demo.py does all the work, without plotting to a separate file.
Thus it would need a little bit of work to support this.

First, I would get rid of line 129-207.
Then, you need to make sure to input: 
- kp_src (support keypoint locations) - List
- skeleton - List of lists.

The rest of the code should be fine for your needs.

**Comment by haoz19** [comment]
Thanks so much! Appreciate a lot for your help!

**Comment by orhir** [comment]
You are welcome. 
Closing this issue, feel free to open a new one if needed.
